import { createRequire } from 'module';
const require = createRequire(import.meta.url);

// Custom server bridge for Hostinger Shared Node.js Hosting
// Created to handle dynamic port mapping and environment variables

// 1. Setup the runtime environment
process.env.NODE_ENV = 'production';
process.env.PORT = process.env.PORT || 3000;

// 2. Load the standalone Next.js server generated by 'output: standalone'
// This file is generated by Next.js in the .next/standalone/server.js folder
try {
  console.log(`🚀 Starting Pragya Pravah on port ${process.env.PORT}...`);
  require('./.next/standalone/server.js');
} catch (error) {
  console.error("❌ CRITICAL: Standalone server not found or failed to start.");
  console.error("👉 Did you run 'npm run build' and upload the '.next/standalone' folder?");
  console.error(error);
  process.exit(1);
}
