var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/aalekh/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__7dc242c4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_466c9296._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5f98963d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/node_modules_next_dist_f9713a08._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/src_5e81d98b._.js")
R.c("server/chunks/ssr/src_app_not-found_tsx_0f6131ce._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_aalekh_error_tsx_e797f67d._.js")
R.c("server/chunks/ssr/src_app_aalekh_loading_tsx_22254cb9._.js")
R.c("server/chunks/ssr/_next-internal_server_app_aalekh_page_actions_857a8f5a.js")
R.m(48102)
module.exports=R.m(48102).exports
